# Generated by Django 2.2.12 on 2020-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
